import time
import uuid

import click
import pytest

from src.benchmark.utils.gh_client import GitHubClient


@pytest.fixture(scope="module")
def real_repo(repo_owner):
    """Fixture to create and delete a temporary real GitHub repository."""
    repo_name = f"temp-test-gh-client-{uuid.uuid4().hex[:8]}"
    full_repo = f"{repo_owner}/{repo_name}"
    client = GitHubClient(repo=full_repo)

    # 1. Create the repository
    success, err = client.create_repo(public=True)
    if not success:
        pytest.fail(f"Failed to create test repository {full_repo}: {err}")

    # Wait for creation to propagate
    time.sleep(3)

    yield client

    # Cleanup: Delete the repository
    success, err = client.delete_repo()
    if not success and err and "delete_repo" in err:
        click.echo(click.style(f"\nWARNING: Could not delete repository {full_repo} due to missing scope.\n", fg="yellow"))
    elif not success:
        click.echo(click.style(f"\nERROR: Could not delete repository {full_repo}: {err}\n", fg="red"))


def test_gh_client_real_operations(real_repo):
    """Real integration test for GitHubClient operations."""
    # 1. Check repo info (should be empty but exist)
    info = real_repo.get_repo_info()
    assert info.get("name") == real_repo.repo.split("/")[-1]
    assert info.get("isEmpty") is True

    # 2. Put a file (initial commit)
    success, err = real_repo.put_file(
        "README.md", "# Test Repo\nGenerated by integration test.", "initial commit", branch="main"
    )
    assert success is True, f"Failed to put README.md: {err}"

    # Wait for propagation
    time.sleep(2)

    # 3. Verify file exists
    sha = real_repo.get_file_sha("README.md", branch="main")
    assert sha is not None

    # 4. List files
    files = real_repo.list_files(branch="main")
    assert "README.md" in files

    # 5. Create a new branch
    success, err = real_repo.create_branch("feature-branch", source_branch="main")
    assert success is True, f"Failed to create feature-branch: {err}"

    # 6. Verify branch exists
    branch_info = real_repo.get_branch_info("feature-branch")
    assert branch_info.get("name") == "feature-branch"

    # 7. Put a file in the new branch
    success, err = real_repo.put_file("feature.txt", "new feature data", "add feature file", branch="feature-branch")
    assert success is True

    # 8. List files on the feature branch
    files = real_repo.list_files(branch="feature-branch")
    assert "feature.txt" in files
    assert "README.md" in files


def test_gh_client_real_fork_and_delete(real_repo, repo_owner):
    """Real integration test for forking and deleting a repository."""
    template = "octocat/Spoon-Knife"
    fork_name = f"temp-fork-{uuid.uuid4().hex[:8]}"
    full_fork = f"{repo_owner}/{fork_name}"

    fork_client = GitHubClient(repo=full_fork)

    # We don't use click.echo here because it's a test, but it's fine if imported
    success, err = fork_client.fork_repo(template)
    if not success:
        pytest.skip(f"Fork failed (maybe already exists or rate limit): {err}")

    # Wait for fork
    time.sleep(10)

    try:
        info = fork_client.get_repo_info()
        assert info is not None
        assert info.get("name") == fork_name

        # Verify it has files from Spoon-Knife
        files = fork_client.list_files(branch="main")
        assert "README.md" in files or "index.html" in files
    finally:
        # 2. Delete the fork
        success, err = fork_client.delete_repo()
        if not success and err and "delete_repo" in err:
            pytest.skip(f"Could not delete fork (missing scope): {err}")
        assert success is True, f"Failed to delete fork: {err}"
