import time
import uuid

import pytest

from src.benchmark.utils.gh_client import GitHubClient

# Use the correct account for testing
REPO_OWNER = "velvetfairy2000"


@pytest.fixture(scope="module")
def real_repo():
    """Fixture to create and delete a temporary real GitHub repository."""
    repo_name = f"temp-test-gh-client-{uuid.uuid4().hex[:8]}"
    full_repo = f"{REPO_OWNER}/{repo_name}"
    client = GitHubClient(repo=full_repo)

    # 1. Create the repository
    success, err = client.create_repo(public=True)
    if not success:
        pytest.fail(f"Failed to create test repository {full_repo}: {err}")

    # Wait for creation to propagate
    time.sleep(5)

    yield client

    # Cleanup: Delete the repository
    # We use -y to confirm and skip the -R if we use the full name as first arg
    # or just use run_gh directly with repo view logic
    client.run_gh(["repo", "delete", full_repo, "--yes"], use_repo=False)


def test_gh_client_real_operations(real_repo):
    """Real integration test for GitHubClient operations."""
    # 1. Check repo info (should be empty but exist)
    info = real_repo.get_repo_info()
    assert info.get("name") == real_repo.repo.split("/")[-1]
    assert info.get("isEmpty") is True

    # 2. Put a file (initial commit)
    success, err = real_repo.put_file(
        "README.md", "# Test Repo\nGenerated by integration test.", "initial commit", branch="main"
    )
    assert success is True, f"Failed to put README.md: {err}"

    # Wait for propagation
    time.sleep(2)

    # 3. Verify file exists
    sha = real_repo.get_file_sha("README.md", branch="main")
    assert sha is not None

    # 4. List files
    files = real_repo.list_files(branch="main")
    assert "README.md" in files

    # 5. Create a new branch
    success, err = real_repo.create_branch("feature-branch", source_branch="main")
    assert success is True, f"Failed to create feature-branch: {err}"

    # 6. Verify branch exists
    branch_info = real_repo.get_branch_info("feature-branch")
    assert branch_info.get("name") == "feature-branch"

    # 7. Put a file in the new branch
    success, err = real_repo.put_file("feature.txt", "new feature data", "add feature file", branch="feature-branch")
    assert success is True

    # 8. List files on the feature branch
    files = real_repo.list_files(branch="feature-branch")
    assert "feature.txt" in files
    assert "README.md" in files
